version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fairplay_db
    restart: always
    environment:
      POSTGRES_USER: fairplay-test
      POSTGRES_PASSWORD: fairplay
      POSTGRES_DB: fairplay-test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Initialize schema automatically if you want (optional)
      # ./schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: